SELECT DISTINCT (STR(?pmidLit) AS ?pmid)
                (STR(?wpidLit) AS ?wpid)
                (CONCAT(STR(?titleLit), " (", STR(?speciesLabelLit), ")") AS ?title)
WHERE {    
  ?pubmed a       wp:PublicationReference ;
          gpml:id ?pmidLit ;
          dcterms:isPartOf ?pathway .
  ?pathway dcterms:identifier ?wpidLit ;
           wp:organismName ?speciesLabelLit ;
           dc:title ?titleLit .
}
ORDER BY ?pmid

