SELECT DISTINCT ?id
                (STR(?wpidLit) AS ?wpid)
                (CONCAT(STR(?titleLit), " (", STR(?speciesLabelLit), ")") AS ?title)
WHERE {    
  ?reference a wp:PublicationReference ;
    gpml:id ?id ; gpml:database "Pubmed" ;
    dcterms:isPartOf* ?pathway .
  ?pathway dcterms:identifier ?wpidLit ;
    wp:organismName ?speciesLabelLit ;
    dc:title ?titleLit .
}
ORDER BY ?pmid ?wpid
